---

parser: "@typescript-eslint/parser"

plugins:
  - "@typescript-eslint"
  - jest
  - prettier
  - simple-import-sort

extends:
  - airbnb-base
  - plugin:@typescript-eslint/recommended
  - plugin:jest/recommended
  - plugin:jest/style
  - prettier
  - prettier/@typescript-eslint


env:
  jest: true

parserOptions:
  ecmaVersion: 6
  sourceType: module

rules:
  import/extensions: off
  import/no-unresolved: off
  import/order: off

  arrow-body-style:
    - error
    - as-needed
    - requireReturnForObjectLiteral: false
  arrow-parens:
    - error
    - as-needed
  class-methods-use-this: off
  curly:
    - error
    - multi-line
    - consistent
  no-console:
    - error
    - allow:
      - info
      - error
  no-else-return:
    - error
    - allowElseIf: false
  no-multi-spaces:
    - error
    - ignoreEOLComments: true
  radix: off

# @typescript-eslint
  # Does not work with class fields :(
  lines-between-class-members:
    - error
    - always
    - exceptAfterSingleLine: true
  "@typescript-eslint/explicit-function-return-type": off
  "@typescript-eslint/explicit-member-accessibility": off
  "@typescript-eslint/explicit-module-boundary-types": off
  "@typescript-eslint/indent": off
  "@typescript-eslint/no-non-null-assertion": off
  "@typescript-eslint/no-object-literal-type-assertion": off

# eslint-plugin-jest
  jest/no-truthy-falsy: error

# simple-import-sort
  simple-import-sort/imports:
    - error
    - groups:
      # Side effect imports.
      - ["^\\u0000"]
      # Packages.
      # Things that start with a letter (or digit or underscore), or `@` followed by a letter.
      - ["^@?\\w"]
      # Absolute imports and other imports such as Vue-style `@/foo`.
      # Anything that does not start with a dot.
      - ["^", "~/"]
      # Relative imports.
      # Anything that starts with a dot.
      - ["^\\."]

# Custom rules
  prefer-early-return: error
